config/routes.rb
Rails.application.routes.draw do

  resources :m_roles
  resources :console_desks

  get :papers_all, :controller=>:papers, :action=>:papers
  resources :papers do
    collection do
      get :show_all
    end
  end

  devise_for :members, controllers: {
    :registrations => "members",
    :sessions      => 'members/sessions'
  }

  resources :members do
    collection do 
      get  :show_all
      post :create_member
    end
  end

  get :mainpage, :controller=>:mainmenus, :action=>:mainpage

  resources :mainmenus do
  end

  root 'mainmenus#mainpage'

end

app/models/paper.rb
class Paper < ActiveRecord::Base
	mount_uploader :avatar, AvatarUploader
end

app/controllers/papers_controller.rb
class PapersController < ApplicationController
  before_action :set_paper, only: [:show, :edit, :update, :destroy]
  # load_and_authorize_resource only: [:exit, :update, :destroy, :new]

  # GET /papers
  # GET /papers.json
  def index
    @papers = Paper.all
  end

  # GET /papers_all
  def show_all
    @papers = Paper.all

    respond_to do |format|
      format.html { render :papers, :layout => "console_desks" }
    end
  end

  # GET /papers/1
  # GET /papers/1.json
  def show
    respond_to do |format|
      format.html { render :layout => "console_desks" }
    end
  end

  # GET /papers/new
  def new
    @paper = Paper.new

    respond_to do |format|
      format.html { render :layout => "console_desks" }
    end
  end

  # GET /papers/1/edit
  def edit
    respond_to do |format|
      format.html { render :layout => "console_desks" }
    end
  end

  # POST /papers
  # POST /papers.json
  def create
    @paper = Paper.new(paper_params)

    respond_to do |format|
      if @paper.save
        format.html { redirect_to @paper, notice: 'Paper was successfully created.' }
        format.json { render :show, status: :created, location: @paper }
      else
        format.html { render :new }
        format.json { render json: @paper.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /papers/1
  # PATCH/PUT /papers/1.json
  def update
    respond_to do |format|
      if @paper.update(paper_params)
        format.html { redirect_to @paper, notice: 'Paper was successfully updated.' }
        format.json { render :show, status: :ok, location: @paper }
      else
        format.html { render :edit }
        format.json { render json: @paper.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /papers/1
  # DELETE /papers/1.json
  def destroy
    @paper.destroy
    respond_to do |format|
      format.html { redirect_to papers_url, notice: 'Paper was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_paper
      @paper = Paper.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def paper_params
      params.require(:paper).permit(:title, :description, :def_flg, :avatar)
    end
end

app/helpers/papers_helper.rb
module PapersHelper
end

app/views/papers/_form.html.erb
<%= form_for(@paper) do |f| %>
  <% if @paper.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@paper.errors.count, "error") %> prohibited this paper from being saved:</h2>

      <ul>
      <% @paper.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="panel panel-default">
  <div class="panel-heading"><h3><%= @paper.persisted? ? "Editing Paper" : "New Paper" %></h3></div>
  <div class="panel-body">

    <div class="field">
      <%= f.label :title %><br>
      <%= f.text_field :title, class: "text_style" %>
    </div>
    <div class="field">
      <%= f.label :description %><br>
      <%= f.text_area :description , class: "text_area_style"%>
    </div>

    <!--  
    <div class="field">
      <%#= f.label :def_flg %><br>
      <%#= f.number_field :def_flg %>
    </div>
    -->

    <div class="field">
      <%= f.file_field :avatar %>
      <%= f.hidden_field :avatar_cache %>
    </div>

    <div class="actions">
      <%= f.submit class: "btn btn-primary" %>&nbsp;
      <%= link_to 'Back', show_all_papers_path, class: "btn btn-default" %>
    </div>

    <%#= link_to 'Show', @paper %> 
    

  </div>
  </div>

<% end %>

app/views/papers/edit.html.erb
<%= render 'form' %>

app/views/papers/index.html.erb
<table class="table">
  <tbody>
    <% @papers.each do |paper| %>
      <tr>
        <td>
            <b>&bull;
              <a href="#" style="color: black">
                <%= paper.title %>
              </a>
            </b>
            <div style="margin-left: 8px">
              <p>
                <%= paper.description %>
                [<%= link_to_if paper.avatar?, "read more", paper.avatar_url, target: "_blank" %>]
              </p>
            </div>
        </td>

      </tr>
    <% end %>
  </tbody>
</table>

app/views/papers/new.html.erb
<%= render 'form' %>

app/views/papers/papers.erb
<p id="notice"><%= notice %></p>

<h1>Listing Papers</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Def flg</th>
      <th>options</th>
    </tr>
  </thead>

  <tbody>
    <% @papers.each do |paper| %>
      <tr>
        <td><%= paper.title %></td>
        <td><%= paper.description %></td>
        <td><%= paper.def_flg %></td>
        <td>
          <%= link_to 'Show', paper, class: "btn btn-default"  %>
          <%= link_to 'Edit', edit_paper_path(paper), class: "btn btn-default"  %>
          <%= link_to 'Destroy', paper, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default"  %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Paper', new_paper_path, class: "btn btn-primary" %>

app/views/papers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @paper.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @paper.description %>
</p>

<p>
  <strong>Def flg:</strong>
  <%= @paper.def_flg %>
</p>
<br>
<br>
<%= image_tag(@paper.avatar_url, style: "width: 150px; height: 150px") if @paper.avatar? %>

<br />

<a href=<%= @paper.avatar_url %> class="media" ><%= @paper.avatar %></a>

<%= link_to 'Edit', edit_paper_path(@paper) %> |
<%= link_to 'Back', papers_path %>