config/routes.rb
Rails.application.routes.draw do

  resources :m_roles
  resources :console_desks

  get :papers_all, :controller=>:papers, :action=>:papers
  resources :papers do
    collection do
      get :show_all
    end
  end

  devise_for :members, controllers: {
    :registrations => "members",
    :sessions      => 'members/sessions'
  }

  resources :members do
    collection do 
      get  :show_all
      post :create_member
    end
  end

  get :mainpage, :controller=>:mainmenus, :action=>:mainpage

  resources :mainmenus do
  end

  root 'mainmenus#mainpage'

end

app/models/m_role.rb
class MRole < ActiveRecord::Base
	has_many :members, :foreign_key => "role"
end

app/controllers/m_roles_controller.rb
class MRolesController < ApplicationController
  before_action :set_m_role, only: [:show, :edit, :update, :destroy]
  protect_from_forgery :except => :destroy

  # GET /m_roles
  # GET /m_roles.json
  def index
    @m_roles = MRole.all

    render layout: "console_desks"
  end

  # GET /m_roles/1
  # GET /m_roles/1.json
  def show
    render layout: "console_desks"
  end

  # GET /m_roles/new
  def new
    @m_role = MRole.new
    render layout: "console_desks"
  end

  # GET /m_roles/1/edit
  def edit
    render layout: "console_desks"
  end

  # POST /m_roles
  # POST /m_roles.json
  def create
    @m_role = MRole.new(m_role_params)

    respond_to do |format|
      if @m_role.save
        format.html { redirect_to @m_role, layout: "console_desks", notice: 'M role was successfully created.' }
        format.json { render :show, status: :created, location: @m_role }
      else
        format.html { render :new }
        format.json { render json: @m_role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /m_roles/1
  # PATCH/PUT /m_roles/1.json
  def update
    respond_to do |format|
      if @m_role.update(m_role_params)
        format.html { redirect_to @m_role, layout: "console_desks", notice: 'M role was successfully updated.' }
        format.json { render :show, status: :ok, location: @m_role }
      else
        format.html { render :edit }
        format.json { render json: @m_role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /m_roles/1
  # DELETE /m_roles/1.json
  def destroy
    @m_role.destroy
    respond_to do |format|
      format.html { redirect_to m_roles_url, notice: 'M role was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_m_role
      @m_role = MRole.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def m_role_params
      params.require(:m_role).permit(:role_no, :role)
    end
end

app/helpers/m_roles_helper.rb
module MRolesHelper
end

app/views/m_roles/_form.html.erb
<%= form_for(@m_role) do |f| %>
  <% if @m_role.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@m_role.errors.count, "error") %> prohibited this m_role from being saved:</h2>

      <ul>
      <% @m_role.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="panel panel-default">
  <div class="panel-heading"><h3><%= @m_role.persisted? ? "Editing M_Role" : "New M_Role" %></h3></div>
  <div class="panel-body">

    <div class="field">
      <%= f.label :role_no %><br>
      <%= f.text_field :role_no, class: "text_style" %>
    </div>
    <div class="field">
      <%= f.label :role %><br>
      <%= f.text_field :role, class: "text_style" %>
    </div>

    <br />

    <div class="actions">
      <%= f.submit class: "btn btn-primary" %>
      <%#= link_to 'Show', @m_role %> &nbsp;
      <%= link_to 'Back', m_roles_path, class: "btn btn-default" %>
    </div>

  </div>
  </div>

<% end %>

app/views/m_roles/edit.html.erb
<%= render 'form' %>

app/views/m_roles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing M Roles</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Role_no</th>
      <th>Role</th>
      <th style="text-align: center">
        options
      </th>
    </tr>
  </thead>

  <tbody>
    <% @m_roles.each do |m_role| %>
      <tr>
        <td><%= m_role.role_no %></td>
        <td><%= m_role.role %></td>
        <td align="center">
          <%= link_to 'Show', m_role, class: "btn btn-default"  %>
          <%= link_to 'Edit', edit_m_role_path(m_role), class: "btn btn-default"  %>
          <%= link_to 'Destroy', m_role, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default"  %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New a role', new_m_role_path, class: "btn btn-primary" %>

app/views/m_roles/new.html.erb
<%= render 'form' %>

app/views/m_roles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Role no:</strong>
  <%= @m_role.role_no %>
</p>

<p>
  <strong>Role:</strong>
  <%= @m_role.role %>
</p>

<%= link_to 'Edit', edit_m_role_path(@m_role) %> |
<%= link_to 'Back', m_roles_path %>