config/routes.rb
Rails.application.routes.draw do

  resources :m_roles
  resources :console_desks

  get :papers_all, :controller=>:papers, :action=>:papers
  resources :papers do
    collection do
      get :show_all
    end
  end

  devise_for :members, controllers: {
    :registrations => "members",
    :sessions      => 'members/sessions'
  }

  resources :members do
    collection do 
      get  :show_all
      post :create_member
    end
  end

  get :mainpage, :controller=>:mainmenus, :action=>:mainpage

  resources :mainmenus do
  end

  root 'mainmenus#mainpage'

end

app/models/member.rb
class Member < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  belongs_to :m_roles, :foreign_key => "role_no"

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  mount_uploader :avatar, AvatarUploader

  default_scope { where(:del_flg => 0) }

end

app/controllers/members/confirmations_controller.rb
class Members::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/members/omniauth_callbacks_controller.rb
class Members::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/members/passwords_controller.rb
class Members::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/members/registrations_controller.rb
class Members::RegistrationsController < Devise::RegistrationsController
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    puts 111111111111111111111111111
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/members/sessions_controller.rb
class Members::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]
protect_from_forgery :except => :destroy

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  def destroy
    super
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/members/unlocks_controller.rb
class Members::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :set_member, only: [:show, :edit, :update, :destroy]

  # GET /members
  # GET /members.json
  def index
    @members = Member.all
  end

  # show all members on comsole desk
  def show_all
    @members = Member.unscoped.all

    respond_to do |format|
      format.html { render "members", layout: "console_desks" }
    end

  end

  # GET /members/1
  # GET /members/1.json
  def show
    respond_to do |format|
      format.html { render :layout => "console_desks" }
    end
  end

  # GET /members/new
  def new
    @member = Member.new
  end

  # GET /members/1/edit
  def edit

    respond_to do |format|
      format.html { render :layout => "console_desks" }
    end
  end

  # POST /members
  # POST /members.json
  def create
    @member = Member.new(member_params)
    puts member_params

    respond_to do |format|
      if @member.save
        format.html { redirect_to @member, notice: 'Member was successfully created.' }
        format.json { render :show, status: :created, location: @member }
      else
        format.html { render :new }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /members/1
  # PATCH/PUT /members/1.json
  def update
    # puts member_params
    # member_params.avatar = member_params[:file]

    respond_to do |format|
      if @member.update(member_params)
        format.html { redirect_to @member, notice: 'Member was successfully updated.' }
        format.json { render :show, status: :ok, location: @member }
      else
        format.html { render :edit }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.json
  def destroy
    @member.destroy
    respond_to do |format|
      format.html { redirect_to members_url, notice: 'Member was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member
      @member = Member.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def member_params
      # params[:member]
      params.require(:member).permit!
      # (:email, :name, :birthday, :date_in, :graduated_from, :role, :status, :del_flg, :avatar, :right)
    end
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/members/_form.html.erb
<%= form_for(@member) do |f| %>
  <% if @member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@member.errors.count, "error") %> prohibited this member from being saved:</h2>

      <ul>
      <% @member.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  

  <div class="panel panel-default">
  <div class="panel-heading"><h3>Editing Member</h3></div>
  <div class="panel-body">
    
    <div class="field">
      <%= f.label :email %><br>
      <%= f.email_field :email, autofocus: true, class: "text_style" %>
    </div>

    <div class="field">
      <%= f.label :password %>
      <% if @minimum_password_length %>
      <em>(<%= @minimum_password_length %> characters minimum)</em>
      <% end %><br />
      <%= f.password_field :password, autocomplete: "off", class: "text_style" %>
    </div>

    <div class="field">
      <%= f.label :password_confirmation %><br />
      <%= f.password_field :password_confirmation, autocomplete: "off", class: "text_style" %>
    </div>


    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name, class: "text_style" %>
    </div>

    <div class="field">
      <%= f.label :birthday %><br>
      <%= f.text_field :birthday, class: "datepicker", class: "text_style" %>
    </div>

    <div class="field">
      <%= f.label :date_in %><br>
      <%= f.text_field :date_in, class: "text_style" %>
    </div>

    <div class="field">
      <%= f.label :graduated_from %><br>
      <%= f.text_field :graduated_from, class: "text_style" %>
    </div>

    <div class="field">
      <%= f.label :role %><br>
      <%= f.select :role, MRole.all.collect{ |mr| [mr.role, mr.role_no] }, { include_blank: true }, { class: "text_style" } %>
      <%#= f.text_field :role %>
    </div>

    <div class="field">
      <%= f.label :status %><br>
      <%= f.text_field :status, class: "text_style" %>
    </div>

    <div class="field">
      <%= f.label :del_flg %><br>
      <%= f.text_field :del_flg, class: "text_style" %>
    </div>

    <div class="field">
      <%= image_tag(@member.avatar_url, style: "width: 150px; height: 150px") if @member.avatar? %>
      <%= f.file_field :avatar %>
      <%= f.hidden_field :avatar_cache, class: "text_style" %>
    </div>

    <br />

    <div class="actions">
      <%= f.submit class: "btn btn-primary" %>
      &nbsp;
      <%= link_to 'Back', show_all_members_path, class: "btn btn-default" %>
    </div>

    <%#= link_to 'Show', @member %>
    

  </div>
  </div>
<% end %>

app/views/members/edit.html.erb
<%= render 'form' %>

app/views/members/index.html.erb
<p id="notice"><%= notice %></p>
<table align="center" width="90%">
  <% @members.each_with_index do |member, index| %>
    <% if cycle('even', 'odd') == "even" %>

      <tr>
        <td width="50%">
          <div style="float: left; display: inline; margin-top: 20px">
            <%= image_tag(member.avatar_url, style: "width: 150px; height: 200px", class: "img-rounded") if member.avatar? %>
          </div>

          <div style="float: left; display: inline; margin-left: 20px; margin-top: 100px">
            <b>name: <%= member.name %></b> 
            <br />
            role: <%= member.role %>
          </div>
        </td>

        <% if index == @members.length-1 %>
          </tr>
        <% end %>

    <% else %>

        <td>
          <div style="float: left; display: inline; margin-top: 20px">
            <%= image_tag(member.avatar_url, style: "width: 150px; height: 200px", class: "img-rounded") if member.avatar? %>
          </div>

          <div style="float: left; display: inline; margin-left: 20px; margin-top: 100px">
            <b>name: <%= member.name %></b> 
            <br />
            role: <%= member.role %>
          </div>
        </td>
      </tr>

    <% end %>
  <% end %>
</table>

app/views/members/members.erb
<p id="notice"><%= notice %></p>

<h1>Listing Members</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>email</th>
      <th>name</th>
      <th>birthday</th>
      <th>date_in</th>
      <th>graduated_from</th>
      <th>role</th>
      <th>status</th>
      <th>right</th>
      <th>del_flg</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @members.each do |member| %>
      <tr>
        <td><%= member.email %></td>
        <td><%= member.name %></td>
        <td><%= member.birthday.strftime("%Y/%m/%d") if member.birthday.present? %></td>
        <td><%= member.date_in.strftime("%Y/%m/%d") if member.date_in.present? %></td>
        <td><%= member.graduated_from %></td>
        <td><%= member.role %></td>
        <td><%= member.status %></td>
        <td><%= member.m_right %></td>
        <td><%= member.del_flg %></td>

        <td>
          <div class="btn-group" role="group" aria-label="...">
            <nobr>
              <%= link_to 'Show', member, class: "btn btn-default" %>
              <%= link_to 'Edit', edit_member_path(member) , class: "btn btn-default" %>
              <%= link_to 'Destroy', member, class: "btn btn-default", method: :delete, data: { confirm: 'Are you sure?' } %>
            </nobr>
          </div>
        </td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Member',  new_member_path, class: "btn btn-primary" %>

app/views/members/new.html.erb
<h2>Sign up</h2>

<%= form_for(@member) do |f| %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password, autocomplete: "off" %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation, autocomplete: "off" %>
  </div>

  <div class="actions">
    <%= f.submit "Sign up" %>
  </div>
<% end %>

app/views/members/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_member_path(@member) %> |
<%= link_to 'Back', members_path %>